### PR TITLE
CAMP-8 About Docs

### PR DESCRIPTION
**Pull request by hariwij**
- Group teams & leads (Backend Dev, frontend dev, Content, UI/UX, etc.)
- Still Teams are not formed yet. So i included following teams and person who inchage of that team.
- _UI/UX_
-   _Graphics_
-   _Content_
-   _Frontend_
-   _Backend_

### CODE REVIEW

**Review by geethakash — COMMENTED** [review]
Who's the lead in Graphics? As I remember it's Senuri not Daya right? 🤔  
@kesaralive

**Review by kesaralive — COMMENTED** [review]
Make sure all the members are in the about doc. 
I see some of our squad members are not there.
Please include them as well. @hariwij

**Comment by kesaralive** [comment]
@geethakash Yes, you're right. In this project she should be the leader. Daya will act as an adviser.

**Review by kesaralive — APPROVED** [review]
Looks good. ✅

**Pull request merged**
